databases:
  - name: recipe
    databaseName: recipe_c89l
    user: recipe_c89l_user

services:
  - type: web
    name: buget-app
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: recipe_c89l
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false